sudo: true

language: go

go:
  - 1.11.x

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

before_script:
  - psql -c "create database testing;" -U postgres

env:
  global:
    - GO111MODULE=on
    - DATABASE_DRIVER=postgres
    - DATABASE_CONN="host=127.0.0.1 port=5432 user=postgres dbname=testing sslmode=disable"
    - DATABASE_URL="postgres://postgres@localhost:5432/testing?sslmode=disable"
    - PGPORT=5433

script:
  - go build ./...
  - go build -o captainslog-migrate cmd/captainslog-migrate/main.go
  - ./captainslog-migrate up
  - go test ./... -v
