sudo: true

language: go

go:
  - 1.11.x

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

env:
  global:
    - GO111MODULE=on
    - DATABASE_DRIVER=postgres
    - DATABASE_CONN="host=127.0.0.1 port=5433 user=testuser dbname=testdb sslmode=disable"
    - DATABASE_URL="postgres://testuser@localhost:5433/testdb?sslmode=disable"
    - PGPORT=5433

before_script:
  - sudo -u postgres psql -c "create user testuser"
  - sudo -u postgres psql -c "alter role testuser superuser"
  - sudo -u postgres psql -c "create database testdb;" -U postgres

script:
  - go build ./...
  - go build -o captainslog-migrate cmd/captainslog-migrate/main.go
  - ./captainslog-migrate up
  - go test ./... -v
