name: Internal Services Standard Library

on:
  push:
    paths:
      - shared/service/**
      - .github/workflows/internal_services_stdlib.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Run build
      working-directory: ./shared/service
      run: go build ./...

    - name: Run tests
      working-directory: ./shared/service
      run: go test ./... -v
