name: Legacy App

on:
  push:
    paths-ignore:
      - web/
      - querier/
      - processor/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Install dependencies
      run: go get -v -t -d ./...

    - name: Run build
      run: go build cmd/captainslog/*

    - name: Run tests
      run: go test ./... -v -test.short
