name: Mobile App

on:
  push:
    paths:
      - mobile/**
      - .github/workflows/mobile_app.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install dependencies
      working-directory: ./mobile
      run: npm install

    - name: Run build
      working-directory: ./mobile
      run: npm run compile

    - name: Run linters
      working-directory: ./mobile
      run: npm run lint
