name: Puller App

on:
  push:
    paths:
      - puller/**
      - .github/workflows/puller_app.yml

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.3
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      CAPTAINSLOG_APPLICATION_URL: http://localhost:3001
      CAPTAINSLOG_REDIRECT_URL: http://localhost:3000/connection/callback/captainslog
      DATABASE_USERNAME: postgres
      FITBIT_CLIENT_ID: sample
      FITBIT_CLIENT_SECRET: sample
      FITBIT_REDIRECT_URL: http://localhost:3000/oauth/fitbit
      LASTFM_API_KEY: sample
      LASTFM_API_SECRET: sample
      LASTFM_REDIRECT_URL: http://localhost:3000/callback/lastfm
      RAILS_ENV: test
      SECRET_KEY_BASE: test

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - uses: actions/cache@v1
      with:
        path: puller/vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('puller/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Install PostgreSQL client
      run: sudo apt-get -yqq install libpq-dev

    - name: Install dependencies
      working-directory: ./puller
      run: |
        gem install bundler --version 2.1.4
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Run linters
      working-directory: ./puller
      run: bundle exec rake lint

    - name: Run brakeman
      working-directory: ./puller
      run: bundle exec brakeman

    - name: Setup application database
      working-directory: ./puller
      run: bundle exec rake db:setup

    - name: Run tests
      working-directory: ./puller
      run: bundle exec rake spec
