detectors:
  IrresponsibleModule:
    enabled: false
  ControlParameter:
    enabled: false

directories:
  db/migrate:
    FeatureEnvy:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    TooManyStatements:
      enabled: false
