detectors:
  IrresponsibleModule:
    enabled: false
  ControlParameter:
    enabled: false
  NilCheck:
    enabled: false
  FeatureEnvy:
    exclude:
      - ApplicationController#requested_time
      - Grouping#grouping_prev_next_times

directories:
  db/migrate:
    FeatureEnvy:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    TooManyStatements:
      enabled: false

exclude_paths:
  - vendor
