detectors:
  IrresponsibleModule:
    enabled: false
  ControlParameter:
    enabled: false
  NilCheck:
    enabled: false
  UncommunicativeVariableName:
    exclude:
      - Processor::Client#post # has the variable name 'e', ok since it's in a rescue block
  FeatureEnvy:
    exclude:
      - ApplicationController#requested_time
      - Grouping#grouping_prev_next_times
      - Processor::Client#response # refers to 'data' more than self
  UtilityFunction:
    exclude:
      - ProcessEntryJob#perform
      - Processor::Client#error
      - Processor::Client#ok?

directories:
  db/migrate:
    FeatureEnvy:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    TooManyStatements:
      enabled: false

exclude_paths:
  - vendor
