detectors:
  IrresponsibleModule:
    enabled: false
  ControlParameter:
    enabled: false
  ClassVariable:
    exclude:
      - ExternalServiceTestHelper::DummyRunner # defines "ran" as a class variable
  NilCheck:
    enabled: false
  UncommunicativeVariableName:
    exclude:
      - ExternalService#self.client # has the variable name 'e', ok since it's in a rescue block
      - Job#safe_run # has the variable name 'e', ok since it's in a rescue block
  DuplicateMethodCall:
    enabled: false
  FeatureEnvy:
    enabled: false
  UtilityFunction:
    enabled: false
  TooManyStatements:
    exclude:
      - ExternalService#self.client
  TooManyMethods:
    exclude:
      - Book
  DataClump:
    enabled: false
  LongParameterList:
    exclude:
      - DataSourceFibitTest#weight_result

directories:
  db/migrate:
    FeatureEnvy:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    TooManyStatements:
      enabled: false

exclude_paths:
  - vendor
