detectors:
  IrresponsibleModule:
    enabled: false
  ControlParameter:
    enabled: false
  ClassVariable:
    exclude:
      - ExternalServiceTestHelper::DummyRunner # defines "ran" as a class variable
  NilCheck:
    enabled: false
  UncommunicativeVariableName:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  FeatureEnvy:
    enabled: false
  UtilityFunction:
    enabled: false
  TooManyStatements:
    exclude:
      - ExternalService#self.client
      - Tracing::Rack#call
      - Job#run
  TooManyMethods:
    exclude:
      - Book
  DataClump:
    enabled: false
  LongParameterList:
    exclude:
      - DataSourceFibitTest#weight_result
      - ExternalService#self.client
      - Tracing::ActiveRecord::Subscriber#call

directories:
  db/migrate:
    FeatureEnvy:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    TooManyStatements:
      enabled: false

exclude_paths:
  - vendor
