detectors:
  IrresponsibleModule:
    enabled: false
  ControlParameter:
    enabled: false
  ClassVariable:
    exclude:
      - ExternalServiceTestHelper::DummyRunner # defines "ran" as a class variable
  NilCheck:
    enabled: false
  UncommunicativeVariableName:
    exclude:
      - ExternalService#self.client # has the variable name 'e', ok since it's in a rescue block
  FeatureEnvy:
    enabled: false
  UtilityFunction:
    exclude:
      - ProcessEntryJob#perform
  TooManyStatements:
    exclude:
      - ExternalService#self.client

directories:
  db/migrate:
    FeatureEnvy:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    TooManyStatements:
      enabled: false

exclude_paths:
  - vendor
