detectors:
  IrresponsibleModule:
    enabled: false
  ControlParameter:
    enabled: false
  NilCheck:
    enabled: false
  UncommunicativeVariableName:
    exclude:
      - ExternalService#self.client # has the variable name 'e', ok since it's in a rescue block
  FeatureEnvy:
    exclude:
      - ApplicationController#requested_time
      - Grouping#grouping_prev_next_times
  UtilityFunction:
    exclude:
      - ProcessEntryJob#perform
  TooManyStatements:
    exclude:
      - ExternalService#self.client

directories:
  db/migrate:
    FeatureEnvy:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    TooManyStatements:
      enabled: false

exclude_paths:
  - vendor
